<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>Resources\Civilium.ico</ApplicationIcon>

		<!-- Publicação Portátil com .NET incluso -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

		<!-- IMPORTANTE: Suporte completo a pt-BR -->
		<InvariantGlobalization>false</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Resources\Civilium.ico" />
		<None Remove="Resources\Civilium_ico.ico" />
		<None Remove="Resources\Civilium_splash.jpg" />
		<None Remove="Resources\chrome_claro.png" />
		<None Remove="Resources\chrome_escuro.png" />
		<None Remove="Resources\contato_claro.png" />
		<None Remove="Resources\contato_escuro.png" />
		<None Remove="Resources\selenium-manager.exe" />
		<None Remove="Resources\tema_claro.png" />
		<None Remove="Resources\tema_escuro.png" />
		<None Remove="Resources\timeout_clar.png" />
		<None Remove="Resources\timeout_claro.png" />
		<None Remove="Resources\timeout_escuro.png" />
		<None Remove="Resources\toggle_claro.png" />
		<None Remove="Resources\toggle_escuro.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\Civilium.ico">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Civilium_splash.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\chrome_claro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\chrome_escuro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\contato_claro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\contato_escuro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="Resources\selenium-manager.exe">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Pack>true</Pack>
			<PackagePath>./</PackagePath>
		</Content>
		
		<Content Include="Resources\tema_claro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="Resources\tema_escuro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="Resources\timeout_claro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="Resources\timeout_escuro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="Resources\toggle_claro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="Resources\toggle_escuro.png">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EPPlus" Version="7.1.1" />
		<PackageReference Include="Selenium.Support" Version="4.34.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.34.0" />
		<PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="138.0.7204.16800" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
		  <DesignTimeSharedInput>True</DesignTimeSharedInput>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

</Project>
